# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('distance', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('high_est', models.IntegerField(default=0)),
                ('low_est', models.IntegerField(default=0)),
                ('estimate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddata.Trip'),
        ),
    ]
