# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetails',
            name='day',
            field=models.CharField(default='noneday', max_length=200),
            preserve_default=False,
        ),
    ]
